CC = gcc
CFLAGS = -Wall -pthread

all: produtor_consumidor

produtor_consumidor: produtor_consumidor.c
	$(CC) $(CFLAGS) -o produtor_consumidor produtor_consumidor.c

clean:
	rm -f produtor_consumidor

